### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by xbsdsongnan** [oarriaga/face_classification#1]
can not run? way?
ValueError: Optimizer weight shape (16,) not compatible with provided weight shape (7, 7, 1, 16)

**Comment by oarriaga** [comment]
Hello @xbsdsongnan ,
the problem might be related to the keras version. I am currently using keras 2.0  with tensorflow 1. as backend. Could you verify that you are using the same versions?

**Comment by xbsdsongnan** [comment]
Operating environment：keras-2.0.4 numpy-1.12.1 pyyaml-3.12 scipy-0.19.0 six-1.10.0，tensorflow-1.1.0，python2/python3，opencv2/opencv3。but can not run。
take python3
Error：(python3:5250): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Attempt to unlock mutex that was not locked
take python2
Error：Attempt to unlock mutex that was not locked
please help me .thank you ,you can take email to me,because I send email to you last day.

**Comment by xbsdsongnan** [comment]
datasets/imdb_crop/imdb.mat' can not find

**Comment by oarriaga** [comment]
@xbsdsongnan the datasetes are not given. If you wanted to re-train the network you would have to download them. In the other case, I just accepted a PR that might fix your problem which might be related to the following line ( which you could also just delete ) in the video_test.py file.

`cv2.startWindowThread()`

**Comment by xbsdsongnan** [comment]
Thank you ,i try to it

**Comment by oarriaga** [comment]
Which version of OpenCV are you using?

**Comment by xbsdsongnan** [comment]
python2  and  opencv2.7.13,but i saw your code,so i make python3 and opencv 3.2.0

**Comment by xbsdsongnan** [comment]
because my system can not python3 with opencv2.7.13,so i have two environment,one python2 with opencv 2.7.13,another, python3 with opencv3.20

**Comment by oarriaga** [comment]
Could you tell me the line in which it fails, and along with the error?

**Comment by xbsdsongnan** [comment]
(python3:6172): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(python3:6172): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Attempt to unlock mutex that was not locked

**Comment by xbsdsongnan** [comment]
if run python2 ,Attempt to unlock mutex that was not locked

**Comment by xbsdsongnan** [comment]
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize,
