### ISSUE TITLE
how to load the .hdf5

### ISSUE THREAD

**Issue by jilner** [oarriaga/face_classification#100]
when i load the file  simple_CNN.81-0.96.hdf5,there is a problem 
UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '

**Comment by cotyyang** [comment]
这个问题对预测结果好像没影响。
https://stackoverflow.com/questions/49195189/error-loading-the-saved-optimizer-keras-python-raspberry?rq=1 给出的答案可能需要你重新训练一下模型，在保存的时候做些处理

**Comment by oarriaga** [comment]
Add the flag:
include_optimizer=False 
when loading the model
