### ISSUE TITLE
can you write this in java?

### ISSUE THREAD

**Issue by niezhiyang** [oarriaga/face_classification#11]
I am devoloper of android, this project is important for me. can you write this in java

**Comment by oarriaga** [comment]
Hey @niezhiyang  , thanks for being interested in my project, I really appreciate contributions of any kind. At the moment I am a bit busy so I don't think I can implement this in Java any time soon. However, thanks to the recent shift of Tensorflow to support Java as a 'first-class-citizen' there is certainly the possibility to migrate parts of the code in this repository to fulfill you needs. Keep in mind that you would also need to make OpenCV available to Java though! This should not be too difficult as OpenCV supports Java now as well! However, I have little experience in this regards so you would be on your own here!

If you manage to make some progress, please let me know and maybe you could even make a pull request and contribute.

Again, thank you for your interest!
