### ISSUE TITLE
OpenCV installation

### ISSUE THREAD

**Issue by sebo313** [oarriaga/face_classification#111]
Hello,
when running `python3 video_emotion_color_demo.py` I get following error message:

RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

I tried to reinstall pip3 install opencv-python but that does not solve my problem. Do you install opencv from source? Any idea how to solve my error?

**Comment by globefire** [comment]
Refer this https://stackoverflow.com/questions/20999939/opencv-2-4-8-module-compiled-against-api-version-9 and let me know if it works.

**Comment by knightowl2704** [comment]
> Hello,
> when running `python3 video_emotion_color_demo.py` I get following error message:
> 
> RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
> 
> I tried to reinstall pip3 install opencv-python but that does not solve my problem. Do you install opencv from source? Any idea how to solve my error?

You need to probably update your numpy version.
