### ISSUE TITLE
how to trained the detection_model?

### ISSUE THREAD

**Issue by MarsTT** [oarriaga/face_classification#117]

**Comment by oarriaga** [comment]
Hi the detection model is the openCV default model.
Here is a tutorial on how to train it:
https://docs.opencv.org/trunk/dc/d88/tutorial_traincascade.html

**Comment by Gauravajariwal11** [comment]
@oarriaga do you know how I can integrate your emotion recognition code with openCV DNN for face detection? https://towardsdatascience.com/extracting-coefficients-of-opencv-face-detection-dnn-model-7f3d944898b9
