### ISSUE TITLE
Emotion labels 

### ISSUE THREAD

**Issue by szhernovoy** [oarriaga/face_classification#13]
Hi,

in the utils/get_labels() there is a code:
```
return {0:'angry',1:'disgust',2:'sad',3:'happy',
                    4:'sad',5:'surprise',6:'neutral'}
```
that looks like typo (2:'sad' and 4:'sad' too). Or that was done on purpose?

**Comment by oarriaga** [comment]
Hello,
@szhernovoy yes it was originally done on purpose due to the unbalanced data. I forgot to change it back, but I just merged a PR that fixes this issue.
