### ISSUE TITLE
Emotion recognition model

### ISSUE THREAD

**Issue by flysprtie** [oarriaga/face_classification#14]
HELLO,Oarriaga! I want to know the architecture about the following CNN Models.Would you like to introducing architecture  of these models. What's differences between two models? 
simple_CNN.530-0.65.hdf5
simple_CNN.985-0.66.hdf5

**Comment by oarriaga** [comment]
Their difference is the number of epochs the models got trained in which in this case are 530 and 985.

**Comment by flysprtie** [comment]
Thank you very much!
