### ISSUE TITLE
Using dlib for detection

### ISSUE THREAD

**Issue by Zumbalamambo** [oarriaga/face_classification#22]
Will using dlib for detection make accuracy better? The accuracy is low during real time prediction because of the offset

**Comment by oarriaga** [comment]
I believe the detection is working properly, and dlib will probably not increase the accuracy of the classifications. However, it might  be better for detection when it comes to slight head rotations which are problematic in the current openCV face detection function.

**Comment by Zumbalamambo** [comment]
why is that it is not detecting asian faces? is it because imdb has only westerners faces?

**Comment by oarriaga** [comment]
I didn't know this problem existed. If is not detecting correctly any sort of faces it only depends on the openCV detection module. It might work better with dlib. I will gladly accept a pull request with this change.

**Comment by oarriaga** [comment]
BTW, when you say detection is not working you are referring to the fact that bounding boxes are not being drawn in Asian faces? Or that the bounding boxes are there but the classification of the emotion/gender is not working?

**Comment by Zumbalamambo** [comment]
it can draw bounding boxes. However,recognition is not accurate. I have tried imwrite the cropped face that Im passing to the model. It is not detecting any of such cropped asian faces.

**Comment by Zumbalamambo** [comment]
If I have to add images to the imdb with asian faces, will it work? if so How do I go about sorting the dataset so I can use it for training

**Comment by Zumbalamambo** [comment]
imdb has very very less amount of asian faces

**Comment by oarriaga** [comment]
Yes if you expand your data it will help.

**Comment by Zumbalamambo** [comment]
Alright I will openup pull request  expanded model. Do you have any idea about how data has to be organized as in imdb so I can retrain the existing model?

**Comment by oarriaga** [comment]
Please look at the source code I believe it shouldn't be to complicated to understand. The inputs shape is organized as follow (num_samples, height, width, num_channels) the outputs shape (num_samples, num_classes).

**Comment by Zumbalamambo** [comment]
It makes use of imdb.mat file. How do I annotate the dataset with  mat file?
