### ISSUE TITLE
Why whoever is predicted to "man" ?

### ISSUE THREAD

**Issue by Jinkeycode** [oarriaga/face_classification#29]
When I run your model，I get this result：
![predicted_test_image](https://user-images.githubusercontent.com/12148377/29758347-56fb5986-8be5-11e7-87f7-e410421c19dd.png)

rather than your example：
![robocup_team](https://user-images.githubusercontent.com/12148377/29758375-a6fba80a-8be5-11e7-901b-fe912f52ece4.png)

**Comment by oarriaga** [comment]
There is a variable in the code called "offset". This has be dynamically changed in accordance to the bounding box size. And I haven't given the time to program it. If I recall correctly I change that variable to zero when running this image.
