### ISSUE TITLE
Feature request: Docker environment

### ISSUE THREAD

**Issue by maxsu** [oarriaga/face_classification#3]
Is there any plan to include a docker/nvidia-docker environment?
Would you be interested in a pull request if I build one?

**Comment by oarriaga** [comment]
Hello @maxsu,
I am currently no thinking of creating a docker image. However, I would gladly accept a pull request with the docker environment.
Thank you.

**Comment by wilderrodrigues** [comment]
Hi @oarriaga ,

Please check my PR. I added the Docker compliance yesterday.

Cheers,
Wilder

**Comment by Zumbalamambo** [comment]
@wilderrodrigues ,May I know where you have pushed the docker compliance? I wish to use it

**Comment by Zumbalamambo** [comment]
it throws the following error

 File "video_test.py", line 33, in <module>
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:9716: error: (-215) scn == 3 || scn == 4 in function cv::cvtColor
