### ISSUE TITLE
A camera photo  predicted in a time frame

### ISSUE THREAD

**Issue by taiwotman** [oarriaga/face_classification#35]
I see that in motion video, the prediction varies a lot and it is hard to have a fixed value compare to when it is, in fact, a static image photo with facial recognition and accurate prediction.

Hence, for motion video, is there a way to have a camera photo that is predicted in a time frame?

**Comment by oarriaga** [comment]
Hello thank you for your interest,
Yes, this is a problem. My basic solution was to have a window of  predictions from the video and then take the mode of the predictions.
The window size is a hyper-parameter that you can play with for your specific purpose. I hope this helps you!
