### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sercanerhan** [oarriaga/face_classification#36]
Should the second python file be training for the gender?

Download the fer2013.tar.gz file from here

Move the downloaded file to the datasets directory inside this repository.

Untar the file:

tar -xzf fer2013.tar
Run the train_emotion_classification.py file
python3 train_emotion_classifier.py
To train previous/new models for gender classification:

Download the imdb_crop.tar file from here (It's the 7GB button with the tittle Download faces only).

Move the downloaded file to the datasets directory inside this repository.

Untar the file:

tar -xfv imdb_crop.tar
**Run the train_emotion_classification.py file
python3 train_emotion_classifier.py**

**Comment by oarriaga** [comment]
Fixed thank you :)!
