### ISSUE TITLE
question about requirements

### ISSUE THREAD

**Issue by lifeiove** [oarriaga/face_classification#38]
Hi@aorriaga
Thanks for your sharing!
I used this code but I have a question.What is the statistics in your requirements?Is it statsmodel in python or others?When I used it ,it will raise:  
### File "video_emotion_color_demo.py", line 1, in <module>
       from statistics import mode
      ImportError: No module named statistics  ###
I found some way,but it didn't work.
Thanks
Lifei

**Comment by mirceaciu** [comment]
`pip install statistics` worked for me

**Comment by lifeiove** [comment]
@mirceaciu Thank you! I used this method before,but it didn't work.Probably a version question.I will try again.Thank you!
