### ISSUE TITLE
simple_CNN

### ISSUE THREAD

**Issue by Play2Boy** [oarriaga/face_classification#39]
hi, I am interested in your project and trained a "simple_CNN" model, but I only got 63.5% accuracy. I also trained your "mini_XCEPTION", I got 65.3%. Anything is wrong with me?

**Comment by lifeiove** [comment]
hello@Play2Boy,I have some question.When I trained ,it didn't work.May need your help.You trained in cpu or gpu?And your system is ubuntu16 or ubuntu14?Thank you!

**Comment by Play2Boy** [comment]
hi @lifeiove , my system is ubuntu14 with gpu.

**Comment by lifeiove** [comment]
Thank you！！！ 发自手机网易邮箱大师 在2017年11月01日 16:23，Play2Boy 写道： hi @lifeiove , my system is ubuntu14 with gpu. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by oarriaga** [comment]
Hello @Play2Boy thank you for your interest in the code,
I think the results you are getting resemble the ones I obtained (65% ~ 66% accuracy with the mini_XCEPTION model). The small difference could be related to the weights initialization.
