### ISSUE TITLE
feature request - python2.7 support

### ISSUE THREAD

**Issue by jeremy-rutman** [oarriaga/face_classification#40]
is python3 strictly required for this? I ran the demo with python2.7 , no errors but no output.  The net seems to load but nothing more. 

```
jeremy@jr:~/projects/face_classification/src$ python image_emotion_gender_demo.py ../images/test_image.jpg 
Using TensorFlow backend.
...
2017-11-02 09:09:55.707876: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
jeremy@jr:~/projects/face_classification/src$ 
```

**Comment by jeremy-rutman** [comment]
actually i just tried in python3 and get same (lack of ) output so I suppose its another issue. Ubuntu16.04, tensorflow 1.4

**Comment by jeremy-rutman** [comment]
whoops my bad , it looks like an output image is getting generated

**Comment by chenjgui** [comment]
are you run successfully?
i have some problem when i use python2.7
"ascii' codec can't decode byte 0xe4 in position24 : ordinal  not in range(128)"

**Comment by chenjgui** [comment]
@jeremy-rutman

**Comment by jeremy-rutman** [comment]
yes this was running fine for me. 
That error looks like maybe you are printing a unicode string.
