### ISSUE TITLE
can not run vdeo_emotion_color_demo.py

### ISSUE THREAD

**Issue by gubiniliya** [oarriaga/face_classification#45]
Hi, I can not start your project.
TF, Keras, OpenCV and other libs installed
What i do
source ./tensorflow/bin/activate //activate TF
(tensorflow) gubiniliya@Lenovo-Z50-75:~/Documents/face_classification-master/src$ python3 video_emotion_color_demo.py
And i have an error
```

Using TensorFlow backend.
/home/gubiniliya/Documents/face_classification-master/src/tensorflow/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
2017-11-30 11:15:39.289068: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX FMA
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 10638
Traceback (most recent call last):
  File "video_emotion_color_demo.py", line 39, in <module>
    gray_image = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2GRAY)
cv2.error: /io/opencv/modules/imgproc/src/color.cpp:10638: error: (-215) scn == 3 || scn == 4 in function cvtColor
```

Okay, i see on line 39 =) 
Yep
    gray_image = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2GRAY)
    rgb_image = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2RGB)
and i found this issue on stackoverflow there they advised us to write the full path to the picture, but we also get video from the camera
bgr_image = video_capture.read()[1]
ok, for test i change bgr_image to "/home/gubiniliya/Images/image.jpg"
And where i do it i have a new error

```
(tensorflow) gubiniliya@Lenovo-Z50-75:~/Documents/face_classification-master/src$ python3 video_emotion_color_demo.py
Using TensorFlow backend.
/home/gubiniliya/Documents/face_classification-master/src/tensorflow/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
2017-11-30 11:28:17.264266: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX FMA
Traceback (most recent call last):
  File "video_emotion_color_demo.py", line 39, in <module>
    gray_image = cv2.cvtColor("/home/gubiniliya/Images/image.jpg", cv2.COLOR_BGR2GRAY)
TypeError: src is not a numpy array, neither a scalar
```

What i need to do, for fix my problem and run projectwith cam

**Comment by mirceaciu** [comment]
I had an similar issue on my embedded Ubuntu board. 

I was using OpenCv installed with `apt-get` or `pip`. My problem was solved after [compiling OpenCv](https://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/)

How did you install OpenCv, and what Os do you use?

**Comment by gubiniliya** [comment]
Ubuntu 17.10 x64 desctop
pip install opencv2-python
or
pip3 install opencv-python
I do not remember exactly, but likely `pip3 install opencv-python`
$ sudo apt-get install opencv
not found this packege

may be i need reinstall opencv?

**Comment by oarriaga** [comment]
You need to compile openCV since the pip installation does not include the VideoCapture functionalities. I would recommend following this [guide](https://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/). Which is the same guide I believe @mirceaciu gave you.

**Comment by gubiniliya** [comment]
Completely following the instructions, I ran into the problem in step where using cmake
The previous steps were fully implemented and passed successfully, but when entering the command
```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=OFF \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.1.0/modules \
    -D PYTHON_EXECUTABLE=~/.virtualenvs/cv/bin/python \
    -D BUILD_EXAMPLES=ON ..
```
in build dir with using `workon cv` where cmake end i have 
```
Configuring incomplete, errors occurred!
See also "/home/gubiniliya/opencv/opencv-3.3.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/gubiniliya/opencv/opencv-3.3.0/build/CMakeFiles/CMakeError.log".
```

I tried restarting with deleting the build folder, but it did not help. I also tried to do this after rebooting - the same result
strange and the fact that the section Python is also not similar to the one in the instruction
I do everything for Python 3
```
-- 
--   Python 2:
--     Interpreter:                 NO
-- 
--   Python 3:
--     Interpreter:                 /home/gubiniliya/.virtualenvs/cv/bin/python3 (ver 3.6.3)
-- 
--   Python (for build):            /home/gubiniliya/.virtualenvs/cv/bin/python3
-- 
```
I'll attach logs, maybe you'll advise something or tell me that you need some option to add or remove
[CMakeError.log](https://github.com/oarriaga/face_classification/files/1527197/CMakeError.log)
[CMakeOutput.log](https://github.com/oarriaga/face_classification/files/1527198/CMakeOutput.log)
Naturally to step make -j I can not go, because the project is not building
