### ISSUE TITLE
Keras 1 models

### ISSUE THREAD

**Issue by crockpotveggies** [oarriaga/face_classification#5]
I was wondering if you still might have your Keras 1 models that you used for this project? And would you be interested in sharing? I'm currently building out a new model zoo for Deeplearning4j, and our importer works for Keras v1 (v2 won't be arriving for 2 months). Thanks!

**Comment by oarriaga** [comment]
Hello @crockpotveggies,
I will look into previous commits and the server in which I was training the models to see if I got any keras1 models. They might not have the same accuracy as these ones or even the same architecture, but I will let you know.

**Comment by crockpotveggies** [comment]
Thanks appreciate it!
