### ISSUE TITLE
create json file

### ISSUE THREAD

**Issue by roiksail** [oarriaga/face_classification#52]
hello everyone...i want to produce json file of video_emotion_gender_demo.py online..do you give me any help??thanks in advance

**Comment by roiksail** [comment]
hello orriaga... please help me...i want to save emotion/gender results in video_emotion_gender_demo.py file results along times that occure in a csv file...please help me...how i do it?

**Comment by oarriaga** [comment]
I will close this issue since is not directly related to the project. You can save the predictions by appending them the output of the CNN in a list and then saving them in csv file with the python csv module.
