### ISSUE TITLE
Specifications regarding the training data

### ISSUE THREAD

**Issue by DonaldTsang** [oarriaga/face_classification#57]
1. What are the dimensions of the training dataset images? Or do they have to be a specific size?
2. Assuming my dataset are photographs instead of "mug-shots", how can I extract the faces from the photos for training using the CNN?
3. Does this project use the same methodology as these two projects, in terms of machine learning and library usage?
    - https://github.com/ageitgey/face_recognition
    - https://cmusatyalab.github.io/openface/

**Comment by oarriaga** [comment]
Thank you for your interest; however, this is not an issue in the code. Please refer to the source code the answer your questions.
