### ISSUE TITLE
How to retrain the model using saved weights?

### ISSUE THREAD

**Issue by mayankjha0220** [oarriaga/face_classification#58]
I have been facing trouble when I try using the saved weights to retrain the train_emotion_classifier model.The model starts from the beginning,no matter what.I tried using the : model.load_model('fer2013_mini_XCEPTION.100-0.65.hdf5') for my 100th epoch.I added this line of code before the model.compile( ) line.

Can you please tell me what changes need to be made if I want to use a weight file from emotion_models folder to retrain the existing model.

**Comment by oarriaga** [comment]
Please refer to the keras website about how to load the models e.g :
```
from keras.models import load_model

model.save('my_model.h5')  # creates a HDF5 file 'my_model.h5'
del model  # deletes the existing model

# returns a compiled model
# identical to the previous one
model = load_model('my_model.h5')
```
