### ISSUE TITLE
About your model when emotion classification

### ISSUE THREAD

**Issue by guoxiaolu** [oarriaga/face_classification#6]
impressive job! You have mentioned "fer2013 emotion classification test accuracy: 66%.". To my knowledge, this result is close to the state of art. But I wanna know some information about your training data. Is it fer2013 train or some other data. And the training data total number is ?
Thank you very much, it is helpful for me~

**Comment by oarriaga** [comment]
Hello @guoxiaolu,
Thank you, yes I believe the current state-of-the-art is around 70%. I am only using the fer2013 training data. I divide the training/test samples in the model.fit function with a 80/20 split.  This should divide it accordingly to the original train/test images from the dataset.

**Comment by guoxiaolu** [comment]
Thank you for your reply~
