### ISSUE TITLE
I have a error when running video_gradcam_demo.py

### ISSUE THREAD

**Issue by pidzvnese** [oarriaga/face_classification#64]
When I trying running video_gradcam_demo.py have an error:  

pidzvnese@piii-pc:~/Desktop/code/face_classification/src$ python3 image_gradcam_demo.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "image_gradcam_demo.py", line 22, in <module>
    image_path = sys.argv[1]
IndexError: list index out of range

Can you help me solve it?

**Comment by stezeo** [comment]
i have same issue. kindly, have you gotten a solution?

**Comment by stezeo** [comment]
@pidzvnese using the image path  of the picture you will like to detect will solve this problem. 

example : image_path = "C:\\Users\\Kasutaja\\Pictures\\barack.img"
