### ISSUE TITLE
 IndexError: list index out of range

### ISSUE THREAD

**Issue by stezeo** [oarriaga/face_classification#67]
kindly, I have this error pumping up each time i try to  run  image_emotion_gender_demo

 IndexError: list index out of range

the error is pointing at :   image_path = sys.argv[1]

@oarriaga please can you respond. I have done several things to see how i could solve this. built a new virtual environment by adhering to the requirement.
existing virtual environment installations are

alabaster                 0.7.10                   py36_0
astroid                   1.5.3                    py36_0
babel                     2.5.0                    py36_0
backports                 1.0                      py36_0
backports.weakref         1.0rc1                   py36_0
bleach                    1.5.0                    py36_0
bzip2                     1.0.6                    vc14_1  [vc14]  conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2016.2.28                py36_0
chardet                   3.0.4                    py36_0
cloudpickle               0.4.0                    py36_0
colorama                  0.3.9                    py36_0
cycler                    0.10.0                   py36_0
decorator                 4.1.2                    py36_0
docutils                  0.14                      <pip>
docutils                  0.14                     py36_0
entrypoints               0.2.3                    py36_0
freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
h5py                      2.7.1                    py36_3    conda-forge
hdf5                      1.10.1                   vc14_2  [vc14]  conda-forge
html5lib                  0.9999999                py36_0
icu                       58.2                     vc14_0  [vc14]  conda-forge
imagesize                 0.7.1                    py36_0
ipykernel                 4.6.1                    py36_0
ipython                   6.1.0                    py36_0
ipython_genutils          0.2.0                    py36_0
isort                     4.2.15                   py36_0
jedi                      0.10.2                   py36_2
jinja2                    2.9.6                    py36_0
jpeg                      9b                       vc14_2  [vc14]  conda-forge
jsonschema                2.6.0                    py36_0
jupyter_client            5.1.0                    py36_0
jupyter_core              4.3.0                    py36_0
Keras                     2.0.5                     <pip>
lazy-object-proxy         1.3.1                    py36_0
libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
libwebp                   0.5.2                    vc14_7  [vc14]  conda-forge
lxml                      3.8.0                    py36_0
markdown                  2.6.9                    py36_0
markupsafe                1.0                      py36_0
matplotlib                2.0.2               np111py36_0
mistune                   0.7.4                    py36_0
mkl                       2017.0.3                      0
nbconvert                 5.2.1                    py36_0
nbformat                  4.4.0                    py36_0
numpy                     1.11.3                   py36_0
numpydoc                  0.7.0                    py36_0
olefile                   0.44                     py36_0
opencv                    3.4.1                  py36_200    conda-forge
openssl                   1.0.2o                   vc14_0  [vc14]  conda-forge
pandas                    0.19.1              np111py36_0
pandocfilters             1.4.2                    py36_0
path.py                   10.3.1                   py36_0
pickleshare               0.7.4                    py36_0
pillow                    5.0.0                    py36_0    conda-forge
pip                       9.0.1                    py36_1
prompt_toolkit            1.0.15                   py36_0
protobuf                  3.5.1               py36_vc14_3  [vc14]  conda-forge
psutil                    5.2.2                    py36_0
pycodestyle               2.3.1                    py36_0
pyflakes                  1.6.0                    py36_0
pygments                  2.2.0                    py36_0
pylint                    1.7.2                    py36_0
pyparsing                 2.2.0                    py36_0
pyqt                      5.6.0                    py36_2
pyreadline                2.1                      py36_0
python                    3.6.2                         0
python-dateutil           2.6.1                    py36_0
pytz                      2017.2                   py36_0
PyYAML                    3.12                      <pip>
pyzmq                     16.0.2                   py36_0
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
qtawesome                 0.4.4                    py36_0
qtconsole                 4.3.1                    py36_0
qtpy                      1.3.1                    py36_0
requests                  2.14.2                   py36_0
rope                      0.9.4                    py36_1
scikit-learn              0.18.1              np111py36_1
scipy                     0.19.0              np111py36_0
setuptools                36.4.0                   py36_1
simplegeneric             0.8.1                    py36_1
singledispatch            3.4.0.3                  py36_0
sip                       4.18                     py36_0
six                       1.10.0                   py36_0
snowballstemmer           1.2.1                    py36_0
sphinx                    1.6.3                    py36_0
sphinxcontrib             1.0                      py36_0
sphinxcontrib-websupport  1.0.1                    py36_0
spyder                    3.2.8                    py36_0    conda-forge
statistics                1.0.3.5                   <pip>
tensorflow                1.2.1                    py36_0
testpath                  0.3.1                    py36_0
Theano                    1.0.1                     <pip>
tk                        8.5.19                   vc14_1  [vc14]  conda-forge
tornado                   4.5.2                    py36_0
traitlets                 4.3.2                    py36_0
vc                        14                            0
vs2015_runtime            14.0.25420                    0
wcwidth                   0.1.7                    py36_0
werkzeug                  0.12.2                   py36_0
wheel                     0.29.0                   py36_0
wincertstore              0.2                      py36_0
wrapt                     1.10.11                  py36_0
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

someone should help please.

**Comment by Azriix** [comment]
You need to give an argument to the program like this : 
`python image_emotion_gender_demo.py image.png`
