### ISSUE TITLE
input dimension

### ISSUE THREAD

**Issue by stezeo** [oarriaga/face_classification#69]
Hello @oarriaga 
Kindly, in your CNN model, you defined the input dimension as (64x64x1).  This dimension is not same as the dimension of the emotion database Fer2013 (48 x 48 x 1).
secondly, what is the dimension of the IMDb? did you just assume (64x64x1) as this was not clear from the  IMDb gender reference page?

**Comment by oarriaga** [comment]
Hi thanks for your interest, yes both gender and emotion have different input sizes. As far as I can remember the IMDb dataset has different image sizes and I reshaped them to 64x64.
