### ISSUE TITLE
实时表情识别如何实现输出是情绪所占百分比

### ISSUE THREAD

**Issue by Lily-123** [oarriaga/face_classification#70]
实时表情识别中，如何实现输出是各个情绪所占百分比，而不是直接某个表情

**Comment by oarriaga** [comment]
Please resubmit in English.

**Comment by jilner** [comment]
您好   为什么我加载模型是总是报错
UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '
