### ISSUE TITLE
How to create my own training dataset 

### ISSUE THREAD

**Issue by aalzooke** [oarriaga/face_classification#75]
Can you please explain how to create my own dataset similar to fer2013? or to add more images to fer2013 to improve the dataset? 
Thank you

**Comment by nishgaba-ai** [comment]
Let's take the example of one of the model files
`
# Reading the model
model_file = "fer2013_mini_XCEPTION.102-0.66.hdf5"`

Now this has an input of shape of [None, 64, 64, 1]
and an output of 7 emotions. But the problem in using the saved files currently for new dataset is they have not saved the optimizer state in the model file. This approach is under transfer learning, you can find the way to load a keras model and use it in your dataset easily.

The other way is to retrain the network provided, the models are declared in "cnn.py" file, or also can be obtained using
`model.summary()`
