### ISSUE TITLE
Can you share the architecture of this project?

### ISSUE THREAD

**Issue by nk0307** [oarriaga/face_classification#77]
I am really lost in the project. Can you show me the flow so I can carry on reading it.

**Comment by nishgaba-ai** [comment]
The model files are already saved in the trained_models folder, it is easy to see the architecture of the models using model.summary(), I am attaching the output of model.summary() output for FER miniXception model file.

`
# Reading the model
import tensorflow as tf

model_file = "fer2013_mini_XCEPTION.102-0.66.hdf5"

model = tf.keras.models.load_model(model_file)
from keras import backend as K
sess = K.get_session()

print(model.summary())

`



![selection_106](https://user-images.githubusercontent.com/30121375/42634184-2a61b238-8600-11e8-8427-a6c5ffac90d4.png)
![selection_105](https://user-images.githubusercontent.com/30121375/42634186-2aa4c9ba-8600-11e8-91e3-c08be232215f.png)


The images are uploaded in reverse order, so this is the whole architecture of the given model
