### ISSUE TITLE
Using new training model

### ISSUE THREAD

**Issue by tombauz** [oarriaga/face_classification#85]
Hello,
first of all the code is great!
The problem is that I'm trying training new models, and when I put one model in the code instead of the "simple CNN" one, it throws an error of the input shape. What can I do?

**_ValueError: Error when checking : expected input_1 to have shape (None, 64, 64, 1) but got array with shape (1, 64, 64, 3)_**

**Comment by oarriaga** [comment]
Thank you, yes you are probably giving RGB images therefore, the 3 at the end of your input tensor. In the original model I only train with grayscale images since the FER2013 dataset only contains  those.

**Comment by tombauz** [comment]
I used the imdb dataset for the gender training (not the emotion). All I need to do is just convert the data in side the new model to grayscale?

**Comment by oarriaga** [comment]
Change the model `input_shape` variable found in the training script to fit your input image shape e. g.  (64, 64, 3)

**Comment by LivingCcj** [comment]
there is a same question?after finished the wiki dataset that download from the same website with imdb,but ValueError: Error when checking : expected input_1 to have shape (None, 64, 64, 1) but got array with shape (1, 64, 64, 3)

**Comment by LivingCcj** [comment]
there is a same question?after finishing the **wiki** dataset that downloaded from the same website (with imdb), i get a new gennder_mini_XCEPTION.05-0.94,when i test a new image,  that give a error:**but ValueError: Error when checking : expected input_1 to have shape (None, 64, 64, 1) but got array with shape (1, 64, 64, 3)**
