### ISSUE TITLE
OSERROR: Unable to open file (emotion_models/fer2013_mini_XCEPTION.102-0.66.hdf5)

### ISSUE THREAD

**Issue by ARehmanZafar** [oarriaga/face_classification#89]
Hi,

As a newbie, I was trying to build this project and get some result out of it. After resolving multiple dependency issues I am now stuck at a point where script tries to execute below:

`emotion_model_path = '../trained_models/emotion_models/fer2013_mini_XCEPTION.102-0.66.hdf5'` 

Time and again loading gets failed with an error as attached below:
![error](https://user-images.githubusercontent.com/43747897/46287818-384e6800-c59d-11e8-9164-050ccd238118.PNG)

I am using Python 3.6.5 with Windows 10 (64-bit). Any help in this regard will be highly appreciated.

Apologies in advance for any inconvenience. Thanks

**Comment by Doch88** [comment]
I think it's a problem of where you're running the script.
Try to change dir to D:\AI\FaceDemo\src\ before running "python image_emotion_gender_demo.py".

**Comment by ARehmanZafar** [comment]
@Doch88 Thanks man. It actually worked. I apologize for being so naive.
