### ISSUE TITLE
Feature request: Documentation

### ISSUE THREAD

**Issue by chrisbward** [oarriaga/face_classification#9]
Very cool, not too familiar with python - just trying to work out the entry point to run the code. How would I plug this in to an image stream?

**Comment by chrisbward** [comment]
Okay, so I managed to get some output;

- commented out the cv2 reference (just couldn't get it installed)
- sudo pip3 install ./REQUIREMENTS.txt
- python3 ./src/image_test.py

Thank you :)

**Comment by oarriaga** [comment]
Hello @chrisbward,
yes installing an specific openCV version could be very complicated. An easy way to install the required openCV version of this project is to install it directly using an [anaconda package](https://anaconda.org/menpo/opencv3) using the following command inside the anaconda environment

`conda install -c menpo opencv3=3.2.0
`

**Comment by davbao** [comment]
Hello, when I run this command : sudo pip install REQUIRMENTS.txt  , it made a mistake:"Could not find a version that satisfies the requirement REQUIREMENTS.txt (from versions:)
No matching distribution found for REQUIREMENTS.txt "
Is this because the python version of the problem? My version is 2.7.12。

**Comment by davbao** [comment]
Excuse me,  I did not understand the problem before that, and now my problem is solved,Thanks very much!

**Comment by wilderrodrigues** [comment]
Hello there, @chrisbward and @davbao,

The is a PR (#16) that adds docker compliance to the project. You won't need any dependency management since everything is now in a docker image.

Let's hope that @oarriaga accepts the PR. :)

Cheers,
Wilder

**Comment by Zumbalamambo** [comment]
Im getting the same error No matching distribution found for REQUIREMENTS.txt "

**Comment by oarriaga** [comment]
I added documentation on how to run the new demo scripts as well as how to train new CNNs :) hope its better. Installation is still relying on pip3 and compiling opencv3.
