### ISSUE TITLE
how to create my own data_manager function

### ISSUE THREAD

**Issue by intvo** [oarriaga/face_classification#94]
I would like to use my own dataset to train the mode, in order to do that i need to create my own data_manager function. 
Here's how my dataset looks like 

Train Folder: 
image-1.jpg
image-2.jpg
image-3.jpg

Test Folder: 
image-1.jpg
image-2.jpg
image-3.jpg

---------

JSON files for test and train look like 

{
    "train": {
          "cat": [
--------Train Images----
--------Train Images----
]
    },
    "test": {
        "cat": [
--------Test Images----
--------Test Images----
]
    }
}
Please share code that will help alot

**Comment by oarriaga** [comment]
I am sorry, this question goes beyond the current limitations of the project.
