### ISSUE TITLE
Inference by taking a list of faces

### ISSUE THREAD

**Issue by florind** [oarriaga/face_classification#95]
I would like to feed a list of images for inference instead of one by one but it doesn't seem to be immediately supported. Since I am not familiar enough with Keras, is there a straight-forward way to change the model to support this?

Thanks,
florin

**Comment by oarriaga** [comment]
I presume you want use a set of consecutive time-spaced images of faces as input to the network. For this you would require the necessary consisting probably of videos. In order to account  for this I took out the mode of a set of predictions withing a giving time window.

**Comment by florind** [comment]
I actually wanted to infer a batch of unrelated images (e.g. each face in https://github.com/oarriaga/face_classification/blob/master/images/robocup_team.png) and get a result array, one value per classified facial expression.
